### ISSUE TITLE
Q: How do you convert TZInfo identifiers to Rails TimeZone name/key?

### ISSUE THREAD

**Issue by TheEricMiller** [jejacks0n/temporal#2]
Great work on this!  Building off what you have here any thoughts on implementing auto detection in rails user form to be stored back to DB?...

*\* How do you convert js values received as TZInfo identifiers to Rails TimeZone name/key? **

FROM: "America/New_York" returned from JavaScript TZinfo detection
TO: "Eastern Time (US & Canada)" convention used in Rails TimeZone

Continued conversation here:
http://stackoverflow.com/questions/14221615/how-to-convert-tzinfo-identifier-to-rails-timezone-name-key

**Comment by henrik** [comment]
@ajbraus The `MAPPING` only includes the subset of time zones that Rails includes in its time zone picker dropdown. There's one here that includes Vancouver: https://gist.github.com/jpmckinney/767070 I suspect it's a complete list but haven't verified.
